<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_api_doc.route_describers.php_doc' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/RouteDescriber/RouteDescriberInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/RouteDescriber/RouteDescriberTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/RouteDescriber/PhpDocDescriber.php';

return $this->services['nelmio_api_doc.route_describers.php_doc'] = new \Nelmio\ApiDocBundle\RouteDescriber\PhpDocDescriber();
