<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ6mn3x4\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ6mn3x4/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZ6mn3x4.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZ6mn3x4\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZ6mn3x4\appProdProjectContainer(array(
    'container.build_hash' => 'Z6mn3x4',
    'container.build_id' => '4a6249d0',
    'container.build_time' => 1518445353,
));
