<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.normalizer.camel_keys_with_leading_underscore' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Normalizer/ArrayNormalizerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Normalizer/CamelKeysNormalizer.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Normalizer/CamelKeysNormalizerWithLeadingUnderscore.php';

return $this->services['fos_rest.normalizer.camel_keys_with_leading_underscore'] = new \FOS\RestBundle\Normalizer\CamelKeysNormalizerWithLeadingUnderscore();
