<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.request.param_fetcher' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Request/ParamFetcherInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Util/ResolverTrait.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Request/ParamFetcher.php';

return $this->services['fos_rest.request.param_fetcher'] = new \FOS\RestBundle\Request\ParamFetcher($this, ${($_ = isset($this->services['fos_rest.request.param_fetcher.reader']) ? $this->services['fos_rest.request.param_fetcher.reader'] : $this->load(__DIR__.'/getFosRest_Request_ParamFetcher_ReaderService.php')) && false ?: '_'}, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, ${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->getValidatorService()) && false ?: '_'});
