<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jms_serializer.naming_strategy' shared service.

include_once $this->targetDirs[3].'/vendor/jms/serializer/src/JMS/Serializer/Naming/PropertyNamingStrategyInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/serializer/src/JMS/Serializer/Naming/CamelCaseNamingStrategy.php';
include_once $this->targetDirs[3].'/vendor/jms/serializer/src/JMS/Serializer/Naming/SerializedNameAnnotationStrategy.php';
include_once $this->targetDirs[3].'/vendor/jms/serializer/src/JMS/Serializer/Naming/CacheNamingStrategy.php';

return $this->services['jms_serializer.naming_strategy'] = new \JMS\Serializer\Naming\CacheNamingStrategy(new \JMS\Serializer\Naming\SerializedNameAnnotationStrategy(new \JMS\Serializer\Naming\CamelCaseNamingStrategy('_', true)));
