<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_api_doc.model_describers.jms' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/ModelDescriber/ModelDescriberInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/Describer/ModelRegistryAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/Describer/ModelRegistryAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/ModelDescriber/JMSModelDescriber.php';

return $this->services['nelmio_api_doc.model_describers.jms'] = new \Nelmio\ApiDocBundle\ModelDescriber\JMSModelDescriber(${($_ = isset($this->services['jms_serializer.metadata_factory']) ? $this->services['jms_serializer.metadata_factory'] : $this->load(__DIR__.'/getJmsSerializer_MetadataFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['jms_serializer.naming_strategy']) ? $this->services['jms_serializer.naming_strategy'] : $this->load(__DIR__.'/getJmsSerializer_NamingStrategyService.php')) && false ?: '_'}, ${($_ = isset($this->services['annotation_reader']) ? $this->services['annotation_reader'] : $this->getAnnotationReaderService()) && false ?: '_'});
