<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_api_doc.generator_locator' shared service.

return $this->services['nelmio_api_doc.generator_locator'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('default' => function () {
    return ${($_ = isset($this->services['nelmio_api_doc.generator']) ? $this->services['nelmio_api_doc.generator'] : $this->load(__DIR__.'/getNelmioApiDoc_GeneratorService.php')) && false ?: '_'};
}));
