<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEfpdtwg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEfpdtwg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEfpdtwg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEfpdtwg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerEfpdtwg\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Efpdtwg',
    'container.build_id' => 'b09c9590',
    'container.build_time' => 1518514322,
));
